### ISSUE TITLE
Vue events not being picked up by livewire, am I doing something wrong?

### ISSUE THREAD

**Issue by zack6849** [livewire/vue#20]
I'm trying to bind the value of a vue component to a livewire property, your docs say anything that fires an input event should be fine

I'm calling this.$emit('input') and nothing is happening to the livewire property, am I missing something?

Related vue component: https://gist.github.com/zack6849/4136077d3b048db19ef13f7c877d4d2c

I'm admittedly not the best at vue, is this a bug, or am I doing something wrong?

Thanks.

**Comment by calebporzio** [comment]
Yeah, Vue doesn't use standard browser events, it uses it's own event system that Livewire won't be able to pick up.

You will need to dispatch the input event with native browser APIs like `element.dispatchEvent(new CustomEvent(...))` (google it for specifics)

Closing. Thanks!
