### ISSUE TITLE
interceptWireModelAttachListener issue with arguments

### ISSUE THREAD

**Issue by jonneroelofs** [livewire/vue#23]
Arguments el and directive are in the wrong order.
debounceIf is not being passed in any more.

**Comment by jonneroelofs** [comment]
possible, but hacky solution: 
![image](https://user-images.githubusercontent.com/20800818/96726774-9df33400-13b2-11eb-9e03-61c621c7ddc4.png)

**Comment by nuke99** [comment]
I have opened a PR for this https://github.com/livewire/vue/pull/27 .
